
```{r}
library(readxl)
library(ggplot2)
library(caTools)
Energyefficiency <- read_excel("ENB2012.xlsx",col_names = TRUE)
#View(Energyefficiency)
dim(Energyefficiency)
```

```{r}
Energyefficiency <- Energyefficiency[,-11]
Energyefficiency <- Energyefficiency[complete.cases(Energyefficiency),]
tail(Energyefficiency)
colnames(Energyefficiency) <- c("Relative.Compactness","Surface.Area","Wall.Area","Roof.Area",
                          "Overall.Height","Orientation","Glazing.Area","Glazing.Area.Distribution",
                                "Heating.Load","Cooling.Load") 
```
```{r}
ggplot() +
  geom_line(aes(x = seq(-1,3,length.out = 187), y = test_set$Cooling.Load, color = 'True')) +
  geom_line(aes(x = seq(-1,3,length.out = 187), y = y_pred,color = 'Predicted'))+
  scale_color_manual(name=' ',values=c(True ='green', Predicted ='blue'))+
  ggtitle('Cooling.Load - True vs Predicted') +
  xlab(' ') +
  ylab('Cooling.Load')
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
